//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarCodeSystem.WebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/U9_LoginNameJudge", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool U9_LoginNameJudge(string UserCode, string UserPassword, string remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetU9UserList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetU9UserList(string user_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSupplierList_ForMES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSupplierList_ForMES(string Org_Code, string Supplier_Code, string Supplier_Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerList_ForMES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCustomerList_ForMES(string Org_Code, string Customer_Code, string Customer_Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemmasterlist_ForMES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetItemmasterlist_ForMES(string Org_Code, string Itemmaster_Code, string Itemmaster_Name, string Itemmaster_Specs, string Itemmaster_Descflexfield);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWhlist_ForMES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetWhlist_ForMES(string Org_Code, string Wh_Code, string Wh_Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUomlist_ForMES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUomlist_ForMES(string Uom_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductlist_ForMES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetProductlist_ForMES(string Org_Code, string Date, string Doc_No);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartmentlist_ForMES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDepartmentlist_ForMES(string Org_Code, string Department_Code, string Department_Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemmasterModifiedOnlist_ForMES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetItemmasterModifiedOnlist_ForMES(string Org_Code, string ModifiedOn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SO(long sOSOLinesID, decimal qty);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BarCodeSystem.WebService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BarCodeSystem.WebService.ServiceSoap>, BarCodeSystem.WebService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool U9_LoginNameJudge(string UserCode, string UserPassword, string remark) {
            return base.Channel.U9_LoginNameJudge(UserCode, UserPassword, remark);
        }
        
        public System.Data.DataSet GetU9UserList(string user_name) {
            return base.Channel.GetU9UserList(user_name);
        }
        
        public System.Data.DataSet GetSupplierList_ForMES(string Org_Code, string Supplier_Code, string Supplier_Name) {
            return base.Channel.GetSupplierList_ForMES(Org_Code, Supplier_Code, Supplier_Name);
        }
        
        public System.Data.DataSet GetCustomerList_ForMES(string Org_Code, string Customer_Code, string Customer_Name) {
            return base.Channel.GetCustomerList_ForMES(Org_Code, Customer_Code, Customer_Name);
        }
        
        public System.Data.DataSet GetItemmasterlist_ForMES(string Org_Code, string Itemmaster_Code, string Itemmaster_Name, string Itemmaster_Specs, string Itemmaster_Descflexfield) {
            return base.Channel.GetItemmasterlist_ForMES(Org_Code, Itemmaster_Code, Itemmaster_Name, Itemmaster_Specs, Itemmaster_Descflexfield);
        }
        
        public System.Data.DataSet GetWhlist_ForMES(string Org_Code, string Wh_Code, string Wh_Name) {
            return base.Channel.GetWhlist_ForMES(Org_Code, Wh_Code, Wh_Name);
        }
        
        public System.Data.DataSet GetUomlist_ForMES(string Uom_Code) {
            return base.Channel.GetUomlist_ForMES(Uom_Code);
        }
        
        public System.Data.DataSet GetProductlist_ForMES(string Org_Code, string Date, string Doc_No) {
            return base.Channel.GetProductlist_ForMES(Org_Code, Date, Doc_No);
        }
        
        public System.Data.DataSet GetDepartmentlist_ForMES(string Org_Code, string Department_Code, string Department_Name) {
            return base.Channel.GetDepartmentlist_ForMES(Org_Code, Department_Code, Department_Name);
        }
        
        public System.Data.DataSet GetItemmasterModifiedOnlist_ForMES(string Org_Code, string ModifiedOn) {
            return base.Channel.GetItemmasterModifiedOnlist_ForMES(Org_Code, ModifiedOn);
        }
        
        public bool upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SO(long sOSOLinesID, decimal qty) {
            return base.Channel.upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SO(sOSOLinesID, qty);
        }
    }
}
