//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace BarCodeSystem.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback U9_LoginNameJudgeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetU9UserListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSupplierList_ForMESOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerList_ForMESOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemmasterlist_ForMESOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWhlist_ForMESOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUomlist_ForMESOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductlist_ForMESOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentlist_ForMESOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemmasterModifiedOnlist_ForMESOperationCompleted;
        
        private System.Threading.SendOrPostCallback upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProjectlist_ForBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStaffRecordListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrglist_ForBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback FaSongDuanXinOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateU9POOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvTrans_ForYWKOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateCompRptOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveCompRptOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateRcvOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWarehouseQtyA1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWarehouseQtyA2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::BarCodeSystem.Properties.Settings.Default.BarCodeSystem_WebService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event U9_LoginNameJudgeCompletedEventHandler U9_LoginNameJudgeCompleted;
        
        /// <remarks/>
        public event GetU9UserListCompletedEventHandler GetU9UserListCompleted;
        
        /// <remarks/>
        public event GetSupplierList_ForMESCompletedEventHandler GetSupplierList_ForMESCompleted;
        
        /// <remarks/>
        public event GetCustomerList_ForMESCompletedEventHandler GetCustomerList_ForMESCompleted;
        
        /// <remarks/>
        public event GetItemmasterlist_ForMESCompletedEventHandler GetItemmasterlist_ForMESCompleted;
        
        /// <remarks/>
        public event GetWhlist_ForMESCompletedEventHandler GetWhlist_ForMESCompleted;
        
        /// <remarks/>
        public event GetUomlist_ForMESCompletedEventHandler GetUomlist_ForMESCompleted;
        
        /// <remarks/>
        public event GetProductlist_ForMESCompletedEventHandler GetProductlist_ForMESCompleted;
        
        /// <remarks/>
        public event GetDepartmentlist_ForMESCompletedEventHandler GetDepartmentlist_ForMESCompleted;
        
        /// <remarks/>
        public event GetItemmasterModifiedOnlist_ForMESCompletedEventHandler GetItemmasterModifiedOnlist_ForMESCompleted;
        
        /// <remarks/>
        public event upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOCompletedEventHandler upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOCompleted;
        
        /// <remarks/>
        public event GetProjectlist_ForBarCodeCompletedEventHandler GetProjectlist_ForBarCodeCompleted;
        
        /// <remarks/>
        public event GetStaffRecordListCompletedEventHandler GetStaffRecordListCompleted;
        
        /// <remarks/>
        public event GetOrglist_ForBarCodeCompletedEventHandler GetOrglist_ForBarCodeCompleted;
        
        /// <remarks/>
        public event FaSongDuanXinCompletedEventHandler FaSongDuanXinCompleted;
        
        /// <remarks/>
        public event CreateU9POCompletedEventHandler CreateU9POCompleted;
        
        /// <remarks/>
        public event GetInvTrans_ForYWKCompletedEventHandler GetInvTrans_ForYWKCompleted;
        
        /// <remarks/>
        public event CreateCompRptCompletedEventHandler CreateCompRptCompleted;
        
        /// <remarks/>
        public event ApproveCompRptCompletedEventHandler ApproveCompRptCompleted;
        
        /// <remarks/>
        public event CreateRcvCompletedEventHandler CreateRcvCompleted;
        
        /// <remarks/>
        public event GetWarehouseQtyA1CompletedEventHandler GetWarehouseQtyA1Completed;
        
        /// <remarks/>
        public event GetWarehouseQtyA2CompletedEventHandler GetWarehouseQtyA2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/U9_LoginNameJudge", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool U9_LoginNameJudge(string UserCode, string UserPassword, string remark) {
            object[] results = this.Invoke("U9_LoginNameJudge", new object[] {
                        UserCode,
                        UserPassword,
                        remark});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void U9_LoginNameJudgeAsync(string UserCode, string UserPassword, string remark) {
            this.U9_LoginNameJudgeAsync(UserCode, UserPassword, remark, null);
        }
        
        /// <remarks/>
        public void U9_LoginNameJudgeAsync(string UserCode, string UserPassword, string remark, object userState) {
            if ((this.U9_LoginNameJudgeOperationCompleted == null)) {
                this.U9_LoginNameJudgeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnU9_LoginNameJudgeOperationCompleted);
            }
            this.InvokeAsync("U9_LoginNameJudge", new object[] {
                        UserCode,
                        UserPassword,
                        remark}, this.U9_LoginNameJudgeOperationCompleted, userState);
        }
        
        private void OnU9_LoginNameJudgeOperationCompleted(object arg) {
            if ((this.U9_LoginNameJudgeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.U9_LoginNameJudgeCompleted(this, new U9_LoginNameJudgeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetU9UserList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetU9UserList(string user_name) {
            object[] results = this.Invoke("GetU9UserList", new object[] {
                        user_name});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetU9UserListAsync(string user_name) {
            this.GetU9UserListAsync(user_name, null);
        }
        
        /// <remarks/>
        public void GetU9UserListAsync(string user_name, object userState) {
            if ((this.GetU9UserListOperationCompleted == null)) {
                this.GetU9UserListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetU9UserListOperationCompleted);
            }
            this.InvokeAsync("GetU9UserList", new object[] {
                        user_name}, this.GetU9UserListOperationCompleted, userState);
        }
        
        private void OnGetU9UserListOperationCompleted(object arg) {
            if ((this.GetU9UserListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetU9UserListCompleted(this, new GetU9UserListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSupplierList_ForMES", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSupplierList_ForMES(string Org_Code, string Supplier_Code, string Supplier_Name) {
            object[] results = this.Invoke("GetSupplierList_ForMES", new object[] {
                        Org_Code,
                        Supplier_Code,
                        Supplier_Name});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSupplierList_ForMESAsync(string Org_Code, string Supplier_Code, string Supplier_Name) {
            this.GetSupplierList_ForMESAsync(Org_Code, Supplier_Code, Supplier_Name, null);
        }
        
        /// <remarks/>
        public void GetSupplierList_ForMESAsync(string Org_Code, string Supplier_Code, string Supplier_Name, object userState) {
            if ((this.GetSupplierList_ForMESOperationCompleted == null)) {
                this.GetSupplierList_ForMESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSupplierList_ForMESOperationCompleted);
            }
            this.InvokeAsync("GetSupplierList_ForMES", new object[] {
                        Org_Code,
                        Supplier_Code,
                        Supplier_Name}, this.GetSupplierList_ForMESOperationCompleted, userState);
        }
        
        private void OnGetSupplierList_ForMESOperationCompleted(object arg) {
            if ((this.GetSupplierList_ForMESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSupplierList_ForMESCompleted(this, new GetSupplierList_ForMESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomerList_ForMES", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCustomerList_ForMES(string Org_Code, string Customer_Code, string Customer_Name) {
            object[] results = this.Invoke("GetCustomerList_ForMES", new object[] {
                        Org_Code,
                        Customer_Code,
                        Customer_Name});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerList_ForMESAsync(string Org_Code, string Customer_Code, string Customer_Name) {
            this.GetCustomerList_ForMESAsync(Org_Code, Customer_Code, Customer_Name, null);
        }
        
        /// <remarks/>
        public void GetCustomerList_ForMESAsync(string Org_Code, string Customer_Code, string Customer_Name, object userState) {
            if ((this.GetCustomerList_ForMESOperationCompleted == null)) {
                this.GetCustomerList_ForMESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerList_ForMESOperationCompleted);
            }
            this.InvokeAsync("GetCustomerList_ForMES", new object[] {
                        Org_Code,
                        Customer_Code,
                        Customer_Name}, this.GetCustomerList_ForMESOperationCompleted, userState);
        }
        
        private void OnGetCustomerList_ForMESOperationCompleted(object arg) {
            if ((this.GetCustomerList_ForMESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerList_ForMESCompleted(this, new GetCustomerList_ForMESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemmasterlist_ForMES", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetItemmasterlist_ForMES(string Org_Code, string Itemmaster_Code, string Itemmaster_Name, string Itemmaster_Specs, string Itemmaster_Descflexfield) {
            object[] results = this.Invoke("GetItemmasterlist_ForMES", new object[] {
                        Org_Code,
                        Itemmaster_Code,
                        Itemmaster_Name,
                        Itemmaster_Specs,
                        Itemmaster_Descflexfield});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemmasterlist_ForMESAsync(string Org_Code, string Itemmaster_Code, string Itemmaster_Name, string Itemmaster_Specs, string Itemmaster_Descflexfield) {
            this.GetItemmasterlist_ForMESAsync(Org_Code, Itemmaster_Code, Itemmaster_Name, Itemmaster_Specs, Itemmaster_Descflexfield, null);
        }
        
        /// <remarks/>
        public void GetItemmasterlist_ForMESAsync(string Org_Code, string Itemmaster_Code, string Itemmaster_Name, string Itemmaster_Specs, string Itemmaster_Descflexfield, object userState) {
            if ((this.GetItemmasterlist_ForMESOperationCompleted == null)) {
                this.GetItemmasterlist_ForMESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemmasterlist_ForMESOperationCompleted);
            }
            this.InvokeAsync("GetItemmasterlist_ForMES", new object[] {
                        Org_Code,
                        Itemmaster_Code,
                        Itemmaster_Name,
                        Itemmaster_Specs,
                        Itemmaster_Descflexfield}, this.GetItemmasterlist_ForMESOperationCompleted, userState);
        }
        
        private void OnGetItemmasterlist_ForMESOperationCompleted(object arg) {
            if ((this.GetItemmasterlist_ForMESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemmasterlist_ForMESCompleted(this, new GetItemmasterlist_ForMESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWhlist_ForMES", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetWhlist_ForMES(string Org_Code, string Wh_Code, string Wh_Name) {
            object[] results = this.Invoke("GetWhlist_ForMES", new object[] {
                        Org_Code,
                        Wh_Code,
                        Wh_Name});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetWhlist_ForMESAsync(string Org_Code, string Wh_Code, string Wh_Name) {
            this.GetWhlist_ForMESAsync(Org_Code, Wh_Code, Wh_Name, null);
        }
        
        /// <remarks/>
        public void GetWhlist_ForMESAsync(string Org_Code, string Wh_Code, string Wh_Name, object userState) {
            if ((this.GetWhlist_ForMESOperationCompleted == null)) {
                this.GetWhlist_ForMESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWhlist_ForMESOperationCompleted);
            }
            this.InvokeAsync("GetWhlist_ForMES", new object[] {
                        Org_Code,
                        Wh_Code,
                        Wh_Name}, this.GetWhlist_ForMESOperationCompleted, userState);
        }
        
        private void OnGetWhlist_ForMESOperationCompleted(object arg) {
            if ((this.GetWhlist_ForMESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWhlist_ForMESCompleted(this, new GetWhlist_ForMESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUomlist_ForMES", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUomlist_ForMES(string Uom_Code) {
            object[] results = this.Invoke("GetUomlist_ForMES", new object[] {
                        Uom_Code});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUomlist_ForMESAsync(string Uom_Code) {
            this.GetUomlist_ForMESAsync(Uom_Code, null);
        }
        
        /// <remarks/>
        public void GetUomlist_ForMESAsync(string Uom_Code, object userState) {
            if ((this.GetUomlist_ForMESOperationCompleted == null)) {
                this.GetUomlist_ForMESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUomlist_ForMESOperationCompleted);
            }
            this.InvokeAsync("GetUomlist_ForMES", new object[] {
                        Uom_Code}, this.GetUomlist_ForMESOperationCompleted, userState);
        }
        
        private void OnGetUomlist_ForMESOperationCompleted(object arg) {
            if ((this.GetUomlist_ForMESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUomlist_ForMESCompleted(this, new GetUomlist_ForMESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductlist_ForMES", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetProductlist_ForMES(string Org_Code, string Date, string Doc_No) {
            object[] results = this.Invoke("GetProductlist_ForMES", new object[] {
                        Org_Code,
                        Date,
                        Doc_No});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductlist_ForMESAsync(string Org_Code, string Date, string Doc_No) {
            this.GetProductlist_ForMESAsync(Org_Code, Date, Doc_No, null);
        }
        
        /// <remarks/>
        public void GetProductlist_ForMESAsync(string Org_Code, string Date, string Doc_No, object userState) {
            if ((this.GetProductlist_ForMESOperationCompleted == null)) {
                this.GetProductlist_ForMESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductlist_ForMESOperationCompleted);
            }
            this.InvokeAsync("GetProductlist_ForMES", new object[] {
                        Org_Code,
                        Date,
                        Doc_No}, this.GetProductlist_ForMESOperationCompleted, userState);
        }
        
        private void OnGetProductlist_ForMESOperationCompleted(object arg) {
            if ((this.GetProductlist_ForMESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductlist_ForMESCompleted(this, new GetProductlist_ForMESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartmentlist_ForMES", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDepartmentlist_ForMES(string Org_Code, string Department_Code, string Department_Name) {
            object[] results = this.Invoke("GetDepartmentlist_ForMES", new object[] {
                        Org_Code,
                        Department_Code,
                        Department_Name});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentlist_ForMESAsync(string Org_Code, string Department_Code, string Department_Name) {
            this.GetDepartmentlist_ForMESAsync(Org_Code, Department_Code, Department_Name, null);
        }
        
        /// <remarks/>
        public void GetDepartmentlist_ForMESAsync(string Org_Code, string Department_Code, string Department_Name, object userState) {
            if ((this.GetDepartmentlist_ForMESOperationCompleted == null)) {
                this.GetDepartmentlist_ForMESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentlist_ForMESOperationCompleted);
            }
            this.InvokeAsync("GetDepartmentlist_ForMES", new object[] {
                        Org_Code,
                        Department_Code,
                        Department_Name}, this.GetDepartmentlist_ForMESOperationCompleted, userState);
        }
        
        private void OnGetDepartmentlist_ForMESOperationCompleted(object arg) {
            if ((this.GetDepartmentlist_ForMESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentlist_ForMESCompleted(this, new GetDepartmentlist_ForMESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemmasterModifiedOnlist_ForMES", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetItemmasterModifiedOnlist_ForMES(string Org_Code, string ModifiedOn) {
            object[] results = this.Invoke("GetItemmasterModifiedOnlist_ForMES", new object[] {
                        Org_Code,
                        ModifiedOn});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemmasterModifiedOnlist_ForMESAsync(string Org_Code, string ModifiedOn) {
            this.GetItemmasterModifiedOnlist_ForMESAsync(Org_Code, ModifiedOn, null);
        }
        
        /// <remarks/>
        public void GetItemmasterModifiedOnlist_ForMESAsync(string Org_Code, string ModifiedOn, object userState) {
            if ((this.GetItemmasterModifiedOnlist_ForMESOperationCompleted == null)) {
                this.GetItemmasterModifiedOnlist_ForMESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemmasterModifiedOnlist_ForMESOperationCompleted);
            }
            this.InvokeAsync("GetItemmasterModifiedOnlist_ForMES", new object[] {
                        Org_Code,
                        ModifiedOn}, this.GetItemmasterModifiedOnlist_ForMESOperationCompleted, userState);
        }
        
        private void OnGetItemmasterModifiedOnlist_ForMESOperationCompleted(object arg) {
            if ((this.GetItemmasterModifiedOnlist_ForMESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemmasterModifiedOnlist_ForMESCompleted(this, new GetItemmasterModifiedOnlist_ForMESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SO(long sOSOLinesID, decimal qty) {
            object[] results = this.Invoke("upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SO", new object[] {
                        sOSOLinesID,
                        qty});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOAsync(long sOSOLinesID, decimal qty) {
            this.upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOAsync(sOSOLinesID, qty, null);
        }
        
        /// <remarks/>
        public void upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOAsync(long sOSOLinesID, decimal qty, object userState) {
            if ((this.upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOOperationCompleted == null)) {
                this.upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOOperationCompleted);
            }
            this.InvokeAsync("upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SO", new object[] {
                        sOSOLinesID,
                        qty}, this.upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOOperationCompleted, userState);
        }
        
        private void OnupDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOOperationCompleted(object arg) {
            if ((this.upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOCompleted(this, new upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProjectlist_ForBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetProjectlist_ForBarCode(string Org_Code, string Project_Code) {
            object[] results = this.Invoke("GetProjectlist_ForBarCode", new object[] {
                        Org_Code,
                        Project_Code});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetProjectlist_ForBarCodeAsync(string Org_Code, string Project_Code) {
            this.GetProjectlist_ForBarCodeAsync(Org_Code, Project_Code, null);
        }
        
        /// <remarks/>
        public void GetProjectlist_ForBarCodeAsync(string Org_Code, string Project_Code, object userState) {
            if ((this.GetProjectlist_ForBarCodeOperationCompleted == null)) {
                this.GetProjectlist_ForBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProjectlist_ForBarCodeOperationCompleted);
            }
            this.InvokeAsync("GetProjectlist_ForBarCode", new object[] {
                        Org_Code,
                        Project_Code}, this.GetProjectlist_ForBarCodeOperationCompleted, userState);
        }
        
        private void OnGetProjectlist_ForBarCodeOperationCompleted(object arg) {
            if ((this.GetProjectlist_ForBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProjectlist_ForBarCodeCompleted(this, new GetProjectlist_ForBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStaffRecordList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetStaffRecordList(string StaffID, string StartDate, string EndDate) {
            object[] results = this.Invoke("GetStaffRecordList", new object[] {
                        StaffID,
                        StartDate,
                        EndDate});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetStaffRecordListAsync(string StaffID, string StartDate, string EndDate) {
            this.GetStaffRecordListAsync(StaffID, StartDate, EndDate, null);
        }
        
        /// <remarks/>
        public void GetStaffRecordListAsync(string StaffID, string StartDate, string EndDate, object userState) {
            if ((this.GetStaffRecordListOperationCompleted == null)) {
                this.GetStaffRecordListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStaffRecordListOperationCompleted);
            }
            this.InvokeAsync("GetStaffRecordList", new object[] {
                        StaffID,
                        StartDate,
                        EndDate}, this.GetStaffRecordListOperationCompleted, userState);
        }
        
        private void OnGetStaffRecordListOperationCompleted(object arg) {
            if ((this.GetStaffRecordListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStaffRecordListCompleted(this, new GetStaffRecordListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrglist_ForBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetOrglist_ForBarCode(string Org_Code) {
            object[] results = this.Invoke("GetOrglist_ForBarCode", new object[] {
                        Org_Code});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrglist_ForBarCodeAsync(string Org_Code) {
            this.GetOrglist_ForBarCodeAsync(Org_Code, null);
        }
        
        /// <remarks/>
        public void GetOrglist_ForBarCodeAsync(string Org_Code, object userState) {
            if ((this.GetOrglist_ForBarCodeOperationCompleted == null)) {
                this.GetOrglist_ForBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrglist_ForBarCodeOperationCompleted);
            }
            this.InvokeAsync("GetOrglist_ForBarCode", new object[] {
                        Org_Code}, this.GetOrglist_ForBarCodeOperationCompleted, userState);
        }
        
        private void OnGetOrglist_ForBarCodeOperationCompleted(object arg) {
            if ((this.GetOrglist_ForBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrglist_ForBarCodeCompleted(this, new GetOrglist_ForBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FaSongDuanXin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FaSongDuanXin(string toMobile, string sendContent, string systemCode, string userCode, string userName, string beiZhu) {
            object[] results = this.Invoke("FaSongDuanXin", new object[] {
                        toMobile,
                        sendContent,
                        systemCode,
                        userCode,
                        userName,
                        beiZhu});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FaSongDuanXinAsync(string toMobile, string sendContent, string systemCode, string userCode, string userName, string beiZhu) {
            this.FaSongDuanXinAsync(toMobile, sendContent, systemCode, userCode, userName, beiZhu, null);
        }
        
        /// <remarks/>
        public void FaSongDuanXinAsync(string toMobile, string sendContent, string systemCode, string userCode, string userName, string beiZhu, object userState) {
            if ((this.FaSongDuanXinOperationCompleted == null)) {
                this.FaSongDuanXinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFaSongDuanXinOperationCompleted);
            }
            this.InvokeAsync("FaSongDuanXin", new object[] {
                        toMobile,
                        sendContent,
                        systemCode,
                        userCode,
                        userName,
                        beiZhu}, this.FaSongDuanXinOperationCompleted, userState);
        }
        
        private void OnFaSongDuanXinOperationCompleted(object arg) {
            if ((this.FaSongDuanXinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FaSongDuanXinCompleted(this, new FaSongDuanXinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateU9PO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateU9PO(System.Data.DataSet myds) {
            object[] results = this.Invoke("CreateU9PO", new object[] {
                        myds});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateU9POAsync(System.Data.DataSet myds) {
            this.CreateU9POAsync(myds, null);
        }
        
        /// <remarks/>
        public void CreateU9POAsync(System.Data.DataSet myds, object userState) {
            if ((this.CreateU9POOperationCompleted == null)) {
                this.CreateU9POOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateU9POOperationCompleted);
            }
            this.InvokeAsync("CreateU9PO", new object[] {
                        myds}, this.CreateU9POOperationCompleted, userState);
        }
        
        private void OnCreateU9POOperationCompleted(object arg) {
            if ((this.CreateU9POCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateU9POCompleted(this, new CreateU9POCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInvTrans_ForYWK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetInvTrans_ForYWK(string Org_Code, string Item_Code) {
            object[] results = this.Invoke("GetInvTrans_ForYWK", new object[] {
                        Org_Code,
                        Item_Code});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetInvTrans_ForYWKAsync(string Org_Code, string Item_Code) {
            this.GetInvTrans_ForYWKAsync(Org_Code, Item_Code, null);
        }
        
        /// <remarks/>
        public void GetInvTrans_ForYWKAsync(string Org_Code, string Item_Code, object userState) {
            if ((this.GetInvTrans_ForYWKOperationCompleted == null)) {
                this.GetInvTrans_ForYWKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvTrans_ForYWKOperationCompleted);
            }
            this.InvokeAsync("GetInvTrans_ForYWK", new object[] {
                        Org_Code,
                        Item_Code}, this.GetInvTrans_ForYWKOperationCompleted, userState);
        }
        
        private void OnGetInvTrans_ForYWKOperationCompleted(object arg) {
            if ((this.GetInvTrans_ForYWKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvTrans_ForYWKCompleted(this, new GetInvTrans_ForYWKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateCompRpt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateCompRpt(System.Data.DataSet myds) {
            object[] results = this.Invoke("CreateCompRpt", new object[] {
                        myds});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateCompRptAsync(System.Data.DataSet myds) {
            this.CreateCompRptAsync(myds, null);
        }
        
        /// <remarks/>
        public void CreateCompRptAsync(System.Data.DataSet myds, object userState) {
            if ((this.CreateCompRptOperationCompleted == null)) {
                this.CreateCompRptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCompRptOperationCompleted);
            }
            this.InvokeAsync("CreateCompRpt", new object[] {
                        myds}, this.CreateCompRptOperationCompleted, userState);
        }
        
        private void OnCreateCompRptOperationCompleted(object arg) {
            if ((this.CreateCompRptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompRptCompleted(this, new CreateCompRptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ApproveCompRpt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ApproveCompRpt(System.Data.DataSet myds) {
            object[] results = this.Invoke("ApproveCompRpt", new object[] {
                        myds});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveCompRptAsync(System.Data.DataSet myds) {
            this.ApproveCompRptAsync(myds, null);
        }
        
        /// <remarks/>
        public void ApproveCompRptAsync(System.Data.DataSet myds, object userState) {
            if ((this.ApproveCompRptOperationCompleted == null)) {
                this.ApproveCompRptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveCompRptOperationCompleted);
            }
            this.InvokeAsync("ApproveCompRpt", new object[] {
                        myds}, this.ApproveCompRptOperationCompleted, userState);
        }
        
        private void OnApproveCompRptOperationCompleted(object arg) {
            if ((this.ApproveCompRptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveCompRptCompleted(this, new ApproveCompRptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateRcv", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateRcv(System.Data.DataSet myds) {
            object[] results = this.Invoke("CreateRcv", new object[] {
                        myds});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateRcvAsync(System.Data.DataSet myds) {
            this.CreateRcvAsync(myds, null);
        }
        
        /// <remarks/>
        public void CreateRcvAsync(System.Data.DataSet myds, object userState) {
            if ((this.CreateRcvOperationCompleted == null)) {
                this.CreateRcvOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateRcvOperationCompleted);
            }
            this.InvokeAsync("CreateRcv", new object[] {
                        myds}, this.CreateRcvOperationCompleted, userState);
        }
        
        private void OnCreateRcvOperationCompleted(object arg) {
            if ((this.CreateRcvCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateRcvCompleted(this, new CreateRcvCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWarehouseQtyA1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetWarehouseQtyA1(string orgCode, string warehouseCode, string date, string itemCode) {
            object[] results = this.Invoke("GetWarehouseQtyA1", new object[] {
                        orgCode,
                        warehouseCode,
                        date,
                        itemCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetWarehouseQtyA1Async(string orgCode, string warehouseCode, string date, string itemCode) {
            this.GetWarehouseQtyA1Async(orgCode, warehouseCode, date, itemCode, null);
        }
        
        /// <remarks/>
        public void GetWarehouseQtyA1Async(string orgCode, string warehouseCode, string date, string itemCode, object userState) {
            if ((this.GetWarehouseQtyA1OperationCompleted == null)) {
                this.GetWarehouseQtyA1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWarehouseQtyA1OperationCompleted);
            }
            this.InvokeAsync("GetWarehouseQtyA1", new object[] {
                        orgCode,
                        warehouseCode,
                        date,
                        itemCode}, this.GetWarehouseQtyA1OperationCompleted, userState);
        }
        
        private void OnGetWarehouseQtyA1OperationCompleted(object arg) {
            if ((this.GetWarehouseQtyA1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWarehouseQtyA1Completed(this, new GetWarehouseQtyA1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWarehouseQtyA2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetWarehouseQtyA2(string orgCode, string warehouseCode, string date, string itemCode) {
            object[] results = this.Invoke("GetWarehouseQtyA2", new object[] {
                        orgCode,
                        warehouseCode,
                        date,
                        itemCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetWarehouseQtyA2Async(string orgCode, string warehouseCode, string date, string itemCode) {
            this.GetWarehouseQtyA2Async(orgCode, warehouseCode, date, itemCode, null);
        }
        
        /// <remarks/>
        public void GetWarehouseQtyA2Async(string orgCode, string warehouseCode, string date, string itemCode, object userState) {
            if ((this.GetWarehouseQtyA2OperationCompleted == null)) {
                this.GetWarehouseQtyA2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWarehouseQtyA2OperationCompleted);
            }
            this.InvokeAsync("GetWarehouseQtyA2", new object[] {
                        orgCode,
                        warehouseCode,
                        date,
                        itemCode}, this.GetWarehouseQtyA2OperationCompleted, userState);
        }
        
        private void OnGetWarehouseQtyA2OperationCompleted(object arg) {
            if ((this.GetWarehouseQtyA2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWarehouseQtyA2Completed(this, new GetWarehouseQtyA2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void U9_LoginNameJudgeCompletedEventHandler(object sender, U9_LoginNameJudgeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class U9_LoginNameJudgeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal U9_LoginNameJudgeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetU9UserListCompletedEventHandler(object sender, GetU9UserListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetU9UserListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetU9UserListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetSupplierList_ForMESCompletedEventHandler(object sender, GetSupplierList_ForMESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSupplierList_ForMESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSupplierList_ForMESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetCustomerList_ForMESCompletedEventHandler(object sender, GetCustomerList_ForMESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerList_ForMESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerList_ForMESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetItemmasterlist_ForMESCompletedEventHandler(object sender, GetItemmasterlist_ForMESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemmasterlist_ForMESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemmasterlist_ForMESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetWhlist_ForMESCompletedEventHandler(object sender, GetWhlist_ForMESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWhlist_ForMESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWhlist_ForMESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetUomlist_ForMESCompletedEventHandler(object sender, GetUomlist_ForMESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUomlist_ForMESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUomlist_ForMESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetProductlist_ForMESCompletedEventHandler(object sender, GetProductlist_ForMESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductlist_ForMESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductlist_ForMESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetDepartmentlist_ForMESCompletedEventHandler(object sender, GetDepartmentlist_ForMESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentlist_ForMESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentlist_ForMESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetItemmasterModifiedOnlist_ForMESCompletedEventHandler(object sender, GetItemmasterModifiedOnlist_ForMESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemmasterModifiedOnlist_ForMESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemmasterModifiedOnlist_ForMESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOCompletedEventHandler(object sender, upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal upDate_PrivateDescSeg1_PrivateDescSeg2_In_SM_SOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetProjectlist_ForBarCodeCompletedEventHandler(object sender, GetProjectlist_ForBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProjectlist_ForBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProjectlist_ForBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetStaffRecordListCompletedEventHandler(object sender, GetStaffRecordListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStaffRecordListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStaffRecordListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetOrglist_ForBarCodeCompletedEventHandler(object sender, GetOrglist_ForBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrglist_ForBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrglist_ForBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void FaSongDuanXinCompletedEventHandler(object sender, FaSongDuanXinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FaSongDuanXinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FaSongDuanXinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CreateU9POCompletedEventHandler(object sender, CreateU9POCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateU9POCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateU9POCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetInvTrans_ForYWKCompletedEventHandler(object sender, GetInvTrans_ForYWKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvTrans_ForYWKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvTrans_ForYWKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CreateCompRptCompletedEventHandler(object sender, CreateCompRptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompRptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompRptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ApproveCompRptCompletedEventHandler(object sender, ApproveCompRptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveCompRptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveCompRptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CreateRcvCompletedEventHandler(object sender, CreateRcvCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateRcvCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateRcvCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetWarehouseQtyA1CompletedEventHandler(object sender, GetWarehouseQtyA1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWarehouseQtyA1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWarehouseQtyA1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetWarehouseQtyA2CompletedEventHandler(object sender, GetWarehouseQtyA2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWarehouseQtyA2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWarehouseQtyA2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591